import { ObjectUtils } from '@/utils/ObjectUtils'

export enum Publicacao {
  NOTICIAS = 'NOTICIAS_GERAIS',
  BALCAO = 'BALCAO_DE_DIREITOS',
  DIREITOS_HUMANOS = 'AREA_ATUACAO_DIREITOS_HUMANOS',
  CONSUMIDOR = 'AREA_ATUACAO_CONSUMIDOR',
  GALERIA = 'GALERIA',
  RECURSAL = 'AREA_ATUACAO_RECURSAL',
  AGRARIO = 'AREA_ATUACAO_AGRARIO_FUNDIARIO',
  MORADIA = 'AREA_ATUACAO_MORADIA',
  FAZENDA = 'AREA_ATUACAO_FAZENDA_PUBLICA',
  VIOLENCIA_GENERO = 'AREA_ATUACAO_VIOLENCIA_GENERO',
  FAMILIA = 'AREA_ATUACAO_FAMILIA',
  INFANCIA_ADOLESCENCIA = 'AREA_ATUACAO_INFANCIA_ADOLESCENCIA',
  PENAL = 'AREA_ATUACAO_EXECUCAO_PENAL',
  CRIMINAL = 'AREA_ATUACAO_CRIMINAL',
  CIVIL = 'AREA_ATUACAO_CIVIL',
  CONSELHO = 'CONSELHO_SUPERIOR',
  CORREGEDORIA = 'CORREGEDORIA',
  LEGISLACOES = 'LEGISLACOES',
  OUVIDORIA = 'OUVIDORIA',
  PUBLICACOES = 'PUBLICACOES_GERAIS',
  PAUTA = 'PAUTA',
  EDITAL = 'EDITAL',
  COMUNICADO = 'COMUNICADO',
}

export const PUBLICACAO_VALUES = ObjectUtils.getEnumKeys(Publicacao)
