import { ObjectUtils } from '@/utils/ObjectUtils'

export enum Transparencia {
  NOTICIAS = 'NOTICIAS_ANEXO',
  TRANSPARENCIA = 'TRANSPARENCIA_ANEXO',
  ADMIN = 'ANEXO_ADMIN',
  GPA = 'INTRANET_OBRAS_DAF_GPA',
  RH = 'INTRANET_RECURSOS_HUMANOS',
  CONTRATOS = 'INTRANET_CONTRATOS',
  DESPESAS = 'INTRANET_DESPESAS_NUPLAN',
  RECEITA = 'INTRANET_RECEITA_NUPLAN',
  CONVENIOS_CLCC = 'INTRANET_CONVENIOS_E_TRANSFERENCIAS_CLCC',
  INSTITUCIONAL = 'INTRANET_INSTITUCIONAL',
  NCI = 'INTRANET_NCI',
  DIARIAS = 'INTRANET_DIÁRIAS',
  LICITAÇÕES_CLCC = 'INTRANET_LICITAÇÕES_CLCC',
  LGPD_GOVERNO = 'INTRANET_LGPD_GOVERNO',
  PLANEJAMENTO = 'INTRANET_PLANEJAMENTO',
}

export const TRANSPARENCIA_VALUES = ObjectUtils.getEnumKeys(Transparencia)
