stages:
  - build
  - send_registry
  - deploy
  - staging

.create_env:
  tags:
    - ssh
  before_script:
    # set env
    - echo "BASE_PATH=$BASE_PATH" > .env

variables:
  GIT_CLEAN_FLAGS: none
  DOCKER_IMAGE_TAG: $CI_COMMIT_SHORT_SHA
