stages:
  - build
  - send_registry
  - deploy
  - staging

.create_env:
  tags:
    - ssh
    - solar-srv1
  before_script:
    # set env
    - echo "BASE_PATH=$BASE_PATH" > .env
    - echo "API_SCPC_URL=$API_SCPC_URL" >> .env

    - echo "SENTRY_DNS=$SENTRY_DNS" >> .env

    - echo "DOMAIN_APPLICATION=$DOMAIN_APPLICATION" >> .env

    # Next Auth
    - echo "NEXT_PUBLIC_API_SCPC_URL=\$API_SCPC_URL" >> .env
    - echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> .env
    - echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env
    - echo "NEXT_PUBLIC_BASE_PATH=\$BASE_PATH" >> .env
    - echo "NEXT_PUBLIC_BASE_NEXT_AUTH=\$BASE_PATH/api/auth" >> .env

    # keycloak Credential
    - echo "KEYCLOACK_BASE=$KEYCLOACK_BASE" >> .env
    - echo "KEYCLOACK_REALM=$KEYCLOACK_REALM" >> .env
    - echo "AUTH_KEYCLOAK_ID=$AUTH_KEYCLOAK_ID" >> .env
    - echo "AUTH_KEYCLOAK_SECRET=$AUTH_KEYCLOAK_SECRET" >> .env

    - echo "NEXT_PUBLIC_TINY_MCE=$NEXT_PUBLIC_TINY_MCE" >> .env


variables:
  GIT_CLEAN_FLAGS: none
  DOCKER_IMAGE_TAG: $CI_COMMIT_SHORT_SHA

include:
  - project: 'devops/gitlab-ci'
    file: '/nextjs/npm/homol.yml'
  - project: 'devops/gitlab-ci'
    file: '/nextjs/npm/prod.yml'
  - project: 'devops/gitlab-ci'
    file: '/nextjs/npm/staging.yml'

