version: '3.9'

x-service: &default-service
  build:
    context: .
    dockerfile: docker/Dockerfile.gitlab
  environment:
    - TZ=America/Belem

services:

  app:
    <<: *default-service
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}

  app_version:
    <<: *default-service
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}-${DOCKER_IMAGE_TAG}
