import { routes } from '@/constants/routes'
import { NavbarItem } from '@/types/NavbarItem'

import {
  IconeBook,
  IconeCalendar,
  IconeCasa,
  IconeCircle,
  IconeFile,
  IconeGauge,
  IconeMoney,
  IconeSlack,
  IconeUsers,
} from './Icons'

export const SidebarData: NavbarItem[] = [
  {
    id: 1,
    permissoes: [],
    title: 'Página Inicial',
    url: routes.HOME,
    icon: IconeCasa,
    subItems: [],
  },
  {
    id: 2,
    permissoes: [
      'DIRETORIA',
      'ADMINISTRATIVO',
      'SUBDEFENSORIA',
      'GGP',
      'CONTROLE_INTERNO',
      'FINANCEIRO',
      'NUPLAN',
      'CORREGEDORIA',
      'ADMINISTRADOR',
      'COORDENADORIA',
      'ESCOLA',
    ],
    title: 'Administrador',
    url: '#',
    icon: IconeGauge,
    subItems: [
      {
        id: 21,
        permissoes: [
          'DIRETORIA',
          'CONTROLE_INTERNO',
          'ADMINISTRADOR',
          'SUBDEFENSORIA',
          'COORDENADORIA',
        ],
        subtitle: 'Lançar Plantão',
        suburl: routes.LANCAR_FOLGA_DIR,
        icon: IconeCircle,
      },
      {
        id: 22,
        permissoes: ['FINANCEIRO', 'ADMINISTRADOR', 'SUBDEFENSORIA'],
        subtitle: 'GGP',
        suburl: routes.GGP,
        icon: IconeCircle,
      },
      {
        id: 23,
        permissoes: [
          'DIRETORIA',
          'ADMINISTRATIVO',
          'SUBDEFENSORIA',
          'GGP',
          'CONTROLE_INTERNO',
          'FINANCEIRO',
          'NUPLAN',
          'CORREGEDORIA',
          'ADMINISTRADOR',
          'COORDENADORIA',
          'ESCOLA',
        ],
        subtitle: 'Status da Solicitação ',
        suburl: routes.SOLICITACAO_STATUS,
        icon: IconeCircle,
      },
    ],
  },
  {
    id: 3,
    permissoes: [
      'DIRETORIA',
      'ADMINISTRATIVO',
      'SUBDEFENSORIA',
      'GGP',
      'CONTROLE_INTERNO',
      'FINANCEIRO',
      'NUPLAN',
      'CORREGEDORIA',
      'ADMINISTRADOR',
      'COORDENADORIA',
      'ESCOLA',
    ],
    title: 'Folga',
    url: '#',
    icon: IconeSlack,
    subItems: [
      {
        id: 31,
        permissoes: ['DIRETORIA', 'ADMINISTRADOR', 'SUBDEFENSORIA'],
        subtitle: 'Aprovar Folgas Diretorias',
        suburl: routes.APROVAR_FOLGA_DIRETORIA,
        icon: IconeCircle,
      },
      {
        id: 32,
        permissoes: ['GERENCIA', 'ADMINISTRADOR', 'SUBDEFENSORIA'],
        subtitle: 'Aprovar Folgas Gerencia',
        suburl: routes.GERENCIA_FOLGA,
        icon: IconeCircle,
      },
      {
        id: 33,
        permissoes: ['COORDENADORIA', 'ADMINISTRADOR', 'SUBDEFENSORIA'],
        subtitle: 'Aprovar Folgas Coordenadoria',
        suburl: routes.ADICIONAR_COORDENADORIA,
        icon: IconeCircle,
      },
      {
        id: 34,
        permissoes: ['ADMINISTRADOR', 'SUBDEFENSORIA'],
        subtitle: 'Gerar Portaria Subdefensoria',
        suburl: routes.CIENCIA_SUBDEFENSORIA,
        icon: IconeCircle,
      },
    ],
  },
  {
    id: 4,
    permissoes: [
      'DIRETORIA',
      'ADMINISTRATIVO',
      'SUBDEFENSORIA',
      'GGP',
      'CONTROLE_INTERNO',
      'FINANCEIRO',
      'NUPLAN',
      'CORREGEDORIA',
      'ADMINISTRADOR',
      'COORDENADORIA',
      'ESCOLA',
    ],
    title: 'Pecúnia',
    url: '#',
    icon: IconeMoney,
    subItems: [
      {
        id: 41,
        permissoes: ['GERENCIA', 'ADMINISTRADOR', 'SUBDEFENSORIA'],
        subtitle: 'Aprovar Pecúnia Gerência ',
        suburl: routes.APROVAR_PECUNIA_GERENCIA,
        icon: IconeCircle,
      },
      {
        id: 42,
        permissoes: ['COORDENADORIA', 'ADMINISTRADOR', 'SUBDEFENSORIA'],
        subtitle: 'Aprovar Pecúnia Coordenadoria ',
        suburl: routes.APROVAR_PECUNIA_COORDENADORIA,
        icon: IconeCircle,
      },
      {
        id: 43,
        permissoes: ['DIRETORIA', 'ADMINISTRADOR', 'SUBDEFENSORIA'],
        subtitle: 'Aprovar Pecúnia Diretoria',
        suburl: routes.APROVAR_PECUNIA_DIRETORIA,
        icon: IconeCircle,
      },
      {
        id: 44,
        permissoes: ['CONTROLE_INTERNO', 'ADMINISTRADOR', 'SUBDEFENSORIA'],
        subtitle: 'Aprovar Pecúnia Controle Interno ',
        suburl: routes.CONTROLE_INTERNO,
        icon: IconeCircle,
      },
      {
        id: 45,
        permissoes: ['NUPLAN'],
        subtitle: 'Nuplan',
        suburl: routes.NUPLAN,
        icon: IconeCircle,
      },
      {
        id: 46,
        permissoes: ['ADMINISTRADOR', 'SUBDEFENSORIA'],
        subtitle: 'Aprovar Pecúnia Subdefensoria',
        suburl: routes.APROVAR_PECUNIA_SUBDEFENSORIA,
        icon: IconeCircle,
      },
      {
        id: 47,
        permissoes: ['FINANCEIRO', 'ADMINISTRADOR', 'SUBDEFENSORIA'],
        subtitle: 'Financeiro',
        suburl: routes.FINANCEIRO,
        icon: IconeCircle,
      },
    ],
  },
  {
    id: 6,
    permissoes: ['ACESSO'],
    title: 'Cursos',
    url: '#',
    icon: IconeBook,
    subItems: [
      {
        id: 61,
        permissoes: ['ACESSO'],
        subtitle: 'Cadastro de Capacitação',
        suburl: routes.REGISTER_COURSE,
        icon: IconeCircle,
      },
      {
        id: 62,
        permissoes: ['ACESSO'],
        subtitle: 'Solicitações',
        suburl: routes.COURSE_REQUESTS,
        icon: IconeCircle,
      },
      {
        id: 63,
        permissoes: ['ACESSO'],
        subtitle: 'Status da Solicitação',
        suburl: routes.COURSE_REQUESTS_STATUS,
        icon: IconeCircle,
      },
    ],
  },
  {
    id: 7,
    permissoes: ['ACESSO'],
    title: 'Escala de Plantão',
    url: '#',
    icon: IconeCalendar,
    subItems: [
      {
        id: 71,
        permissoes: ['ACESSO'],
        subtitle: 'Cadastro de Escala',
        suburl: routes.REGISTER_SCALE,
        icon: IconeCircle,
      },
      {
        id: 72,
        permissoes: ['ACESSO'],
        subtitle: 'Solicitações de Escala de Plantão',
        suburl: routes.APROVAR_ESCALA,
        icon: IconeCircle,
      },
      {
        id: 73,
        permissoes: ['ACESSO'],
        subtitle: 'Històrico das solicitações de Escala de plantão',
        suburl: routes.EDITA_SOLICITACAO_PLANTAO_ESCALA,
        icon: IconeCircle,
      },
    ],
  },
  {
    id: 8,
    permissoes: ['ACESSO'],
    title: 'Relatório',
    url: '#',
    icon: IconeFile,
    subItems: [
      {
        id: 81,
        permissoes: ['ACESSO'],
        subtitle: 'Solicitações',
        suburl: routes.APROVE_SCALE_REPORT,
        icon: IconeCircle,
      },
      {
        id: 82,
        permissoes: ['ACESSO'],
        subtitle: 'Relatório',
        suburl: routes.REGISTER_SCALE_REPORT,
        icon: IconeCircle,
      },
    ],
  },
  {
    id: 5,
    permissoes: ['ACESSO'],
    title: 'Área do Usuário',
    url: '#',
    icon: IconeUsers,
    subItems: [
      {
        id: 51,
        permissoes: ['ACESSO'],
        subtitle: 'Inclusão de Capacitação',
        suburl: routes.USER_INCLUSAO_CURSO,
        icon: IconeCircle,
      },
      {
        id: 52,
        permissoes: ['ACESSO'],
        subtitle: 'Solicitar Folga',
        suburl: routes.SOLICITACAO_FOLGA,
        icon: IconeCircle,
      },
      {
        id: 53,
        permissoes: ['ACESSO'],
        subtitle: 'Solicitar Pecúnia',
        suburl: routes.SOLICITACAO_PECUNIA,
        icon: IconeCircle,
      },
      {
        id: 55,
        permissoes: ['ACESSO'],
        subtitle: 'Solicitações do Servidor',
        suburl: routes.MINHAS_SOLICITACOES,
        icon: IconeCircle,
      },
    ],
  },
]
