import { ANEXO_VALUES } from '@/utils/roles/Anexo'
import { GERENCIA_VALUES } from '@/utils/roles/Gerencia'
import { TRANSPARENCIA_VALUES } from '@/utils/roles/Transparencia'
import { NavbarItem } from '@/types/NavbarItem'
import { routes } from '@/constants/routes'

import { IconeCasa, IconeGauge, IconeCircle } from './Icons'

export const SidebarData: NavbarItem[] = [
  {
    id: 1,
    permissoes: [],
    title: 'Página Inicial',
    url: routes.HOME,
    icon: IconeCasa,
    subItems: [],
  },
  {
    id: 2,
    permissoes: GERENCIA_VALUES,
    title: 'Administrador',
    url: '#',
    icon: IconeGauge,
    subItems: [
      {
        id: 21,
        permissoes: ['ADMIN'],
        subtitle: 'Exemplo de Tabelas',
        suburl: routes.SETORES,
        icon: IconeCircle,
      },
      {
        id: 22,
        permissoes: ['ADMIN', 'uma_authorization', 'ANEXO_ADMIN'],
        subtitle: 'Dashboard',
        suburl: '#',
        icon: IconeGauge, // Alterado aqui
      },
      {
        id: 23,
        permissoes: ['ADMIN', 'uma_authorization', 'ANEXO_ADMIN'],
        subtitle: 'Configurações',
        suburl: '#',
        icon: IconeCircle, // Alterado aqui
      },
      {
        id: 24,
        permissoes: ['ADMIN', 'uma_authorization', 'ANEXO_ADMIN'],
        subtitle: 'Localidade',
        suburl: '#',
        icon: IconeCircle, // Alterado aqui
      },
      {
        id: 25,
        permissoes: ['ADMIN', 'uma_authorization', 'ANEXO_ADMIN'],
        subtitle: 'Meio de Transporte',
        suburl: '#',
        icon: IconeCircle, // Alterado aqui
      },
      {
        id: 26,
        permissoes: ['ADMIN', 'uma_authorization', 'ANEXO_ADMIN'],
        subtitle: 'Perfil',
        suburl: '#',
        icon: IconeCircle, // Alterado aqui
      },
      {
        id: 27,
        permissoes: ['ADMIN', 'uma_authorization', 'ANEXO_ADMIN'],
        subtitle: 'Tipo de Diárias',
        suburl: '#',
        icon: IconeCircle, // Alterado aqui
      },
      {
        id: 28,
        permissoes: ['ADMIN', 'uma_authorization', 'ANEXO_ADMIN'],
        subtitle: 'Tipo de Valor de Diária',
        suburl: '#',
        icon: IconeCircle, // Alterado aqui
      },
    ],
  },
  {
    id: 3,
    permissoes: [],
    title: 'Movimentação',
    url: '#',
    icon: IconeCasa,
    subItems: [
      {
        id: 31,
        permissoes: [],
        subtitle: 'Ação',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 32,
        permissoes: [],
        subtitle: 'Diárias',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 33,
        permissoes: [],
        subtitle: 'Transporte',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 34,
        permissoes: [],
        subtitle: 'Relatório de viagem',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 35,
        permissoes: [],
        subtitle: 'Relatório de viagem (BD)',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 36,
        permissoes: [],
        subtitle: 'Relatório de viagem (BD)',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 37,
        permissoes: [],
        subtitle: 'Coordenação',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 38,
        permissoes: [],
        subtitle: 'Diretoria',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 39,
        permissoes: [],
        subtitle: 'Controle Interno',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 40,
        permissoes: [],
        subtitle: 'Relatório de Perfil',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 41,
        permissoes: [],
        subtitle: 'Relatório Pendentes',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 42,
        permissoes: [],
        subtitle: 'Prestação de Contas',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 43,
        permissoes: [],
        subtitle: 'Nuplan',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 44,
        permissoes: [],
        subtitle: 'Ordenador de Despesas',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 45,
        permissoes: [],
        subtitle: 'Financeiro',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 46,
        permissoes: [],
        subtitle: 'Ordenador de Despesas (BD)',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 47,
        permissoes: [],
        subtitle: 'Minhas Diárias',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 48,
        permissoes: [],
        subtitle: 'Consulta',
        suburl: '#',
        icon: IconeCircle,
      },
    ],
  },
  {
    id: 4,
    permissoes: TRANSPARENCIA_VALUES,
    title: 'GGP',
    url: '#',
    icon: IconeCasa,
    subItems: [
      {
        id: 41,
        permissoes: ANEXO_VALUES,
        subtitle: 'Afastamento',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 42,
        permissoes: ANEXO_VALUES,
        subtitle: 'Banco',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 41,
        permissoes: ANEXO_VALUES,
        subtitle: 'Classificação de Função',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 43,
        permissoes: ANEXO_VALUES,
        subtitle: 'Consulta Extrato',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 44,
        permissoes: ANEXO_VALUES,
        subtitle: 'Coordenação',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 45,
        permissoes: ANEXO_VALUES,
        subtitle: 'Diretoria',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 46,
        permissoes: ANEXO_VALUES,
        subtitle: 'Extrato Publicação',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 47,
        permissoes: ANEXO_VALUES,
        subtitle: 'Feriados',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 48,
        permissoes: ANEXO_VALUES,
        subtitle: 'Função',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 49,
        permissoes: ANEXO_VALUES,
        subtitle: 'Lotação',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 50,
        permissoes: ANEXO_VALUES,
        subtitle: 'Objetivo Padrão',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 51,
        permissoes: ANEXO_VALUES,
        subtitle: 'Orgão',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 52,
        permissoes: ANEXO_VALUES,
        subtitle: 'Servidor',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 53,
        permissoes: ANEXO_VALUES,
        subtitle: 'Setor',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 54,
        permissoes: ANEXO_VALUES,
        subtitle: 'Vinculo',
        suburl: '#',
        icon: IconeCircle,
      },
    ],
  },
  {
    id: 5,
    permissoes: TRANSPARENCIA_VALUES,
    title: 'NUPLAN',
    url: '#',
    icon: IconeCasa,
    subItems: [
      {
        id: 51,
        permissoes: ANEXO_VALUES,
        subtitle: 'Convênio',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 52,
        permissoes: ANEXO_VALUES,
        subtitle: 'Detalhamento de Fonte',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 53,
        permissoes: ANEXO_VALUES,
        subtitle: 'Função Programática',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 54,
        permissoes: ANEXO_VALUES,
        subtitle: 'GPPará',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 55,
        permissoes: ANEXO_VALUES,
        subtitle: 'Naturezadas Despesa',
        suburl: '#',
        icon: IconeCircle,
      },
      {
        id: 56,
        permissoes: ANEXO_VALUES,
        subtitle: 'Plano Interno',
        suburl: '#',
        icon: IconeCircle,
      },
    ],
  },
]
